name: Snapshot Release

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - 'stage/**'
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3
        with:
          distribution: zulu
          java-version: 17
      - name: Publish package
        run: mvn --batch-mode deploy -DreleaseTarget=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
